name: Build Release

on:
  workflow_dispatch:

  pull_request:
    branches:
    - main

jobs:
  Build-Release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install NSIS
      run: |
        Start-Process -FilePath 'NSIS\nsis-3.08-setup.exe' -ArgumentList '/S' -NoNewWindow -Wait
        echo 'Installed successfully.'

    - name: Create Installer
      run: |
        Start-Process -FilePath 'C:/Program Files (x86)/NSIS/makensis.exe' -ArgumentList 'NSIS/Thunder_Professional.nsi' -NoNewWindow -Wait

    - name: Upload Installer to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: ThunderProfessional_Installer
        path: NSIS/ThunderProfessional_Setup.exe

    - name: Make release dir and Copy Installer
      run: |
        mkdir -p release
        Copy-Item -Path "NSIS/ThunderProfessional_Setup.exe" -Destination "release/" -Recurse -Force

    - name: Package portable EXE
      run: |
        Compress-Archive -Path Thunder_Professional -DestinationPath release/ThunderProfessional_Portable.zip
        echo 'Successfully packaged "ThunderProfessional_Portable".'

    - name: Upload portable EXE to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: ThunderProfessional_Portable
        path: release/ThunderProfessional_Portable.zip

    - name: Print files from release dir
      run: ls release -Recurse -Force

    - name: Calculate checksums
      run: pwsh .github/workflows/generate-sha256.ps1 release/

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          release/*.zip
          release/*.exe
        draft: true
        bodyFile: release/checksums.md
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
